### ISSUE TITLE
Question ref: ASUS TUF GAMING Z790-PLUS WIFI D4

### ISSUE THREAD

**Issue by D-an-W** [Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790#2]
Hi and thanks for the effort you put into this!

I have the ASUS TUF GAMING Z790-PLUS WIFI D4 with Ventura installed using an EFI from another with the same board.

Would you consider this a good choice for me to try and build my own with the info you provide please?

Everything seems to work other than sleep, I have built my own USB map which I think it good but doesn't help the sleep issue.

**Comment by Stick-Study** [comment]
Hi and thank you for your support!

I think you're perfectly fine with whatever EFI you use.  I think my repo is just to help some people who don't have any reference to install hackintosh. So if it isn't necessary, you needn't try and build your own EFI. 

About the sleep, please provide more detailed information.  For example, the machine cannot be stopped or cannot be woken up. If it cannot be stopped, you can enter `log show --last 1d | grep "Wake reason"` in the terminal and send me the screenshot.

**Comment by D-an-W** [comment]
Thanks, I will attach the screenshot in a couple of hours when I get home.

**Comment by D-an-W** [comment]
@Fu-Yuxuan-hub here is a screenshot showing the instant wake from sleep.

I have also attached a bootlog to show the ACPI errors I noticed.
[bootlog.txt](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/files/11021229/bootlog.txt)
![Screenshot 2023-03-20 at 17 22 47](https://user-images.githubusercontent.com/2243883/226419623-ff7d36e5-2a90-47c5-b176-3671cd134f71.png)

**Comment by Stick-Study** [comment]
XDCI wakes up, there can be many reasons for it. Such as the bluetooth. I think you may need some time to identify it. The method is to turn off the wake-up method. Such as disabling wake-up from LAN or USB. If you have a Broadcom wireless network card, you can first unplug the USB cable connecting it to the motherboard and try the sleep again. And upload your EFI by the way.

About the ACPI Error: It is because Apple has not updated AppleACPIPlatform, resulting in AE_NOT_FOUND

**Comment by D-an-W** [comment]
Thanks, I will upload it later today and also unplug the Fenvi 919 I have.

**Comment by D-an-W** [comment]
@Fu-Yuxuan-hub the system still wakes with the Fenvi (Broadcom) unplugged, I will post the EFI shortly.

**Comment by D-an-W** [comment]
Here is my EFI, I just removed the Serial numbers etc:

[EFI Current.zip](https://github.com/Fu-Yuxuan-hub/General-EFI-for-H610-B660-Z690-B760-Z790/files/11032713/EFI.Current.zip)

![Screenshot 2023-03-21 at 21 27 39](https://user-images.githubusercontent.com/2243883/226745104-1eed625f-c03f-4f88-834e-b8ae70fbd3a2.png)

Thanks for the help with this, much appreciated!

**Comment by D-an-W** [comment]
@Fu-Yuxuan-hub if I install iCUE for macOS (I have the CORSAIR iCUE H150i ELITE LCD XT and CORSAIR iCUE 5000X RGB) although it doesn't show any of my hardware it does seem to work sleep work on the second try.

First try it wakes instantly but the second try it sleeps normally!

**Comment by Stick-Study** [comment]
@D-an-W I'm sorry I couldn't help you with your sleep problems. Because I have never encountered these devices. I think sleep problems are likely to be the cause of it. You could try disabling wake from USB in BIOS to see if that's the cause. Glad to see you found a solution. And I would ask other people about your sleep. I will also update my Fixing Sleep content.

If it is indeed caused by CORSAIR iCUE H150i ELITE LCD XT. You can try to plug the USB cable into USB3.0 through a converter. Because the Bluetooth of BCM94360CD often has this problem. My solution is to plug the USB cable into the USB3.0 through a converter.

**Comment by D-an-W** [comment]
I think it might be due to the iCUE ELITE I have installed, going to do some more research tonight. 

Does the EFI I uploaded look to be missing anything (not related to sleep)?

**Comment by Stick-Study** [comment]
Did you not enable E-Core? I think you might miss CpuTopologyRebuild.kext to enable 13700K's E-Core.

By the way, does the ethernet work?

**Comment by D-an-W** [comment]
Ethernet does seem to work ok, how do I check if it’s identified correctly?

is E-Core in the BIOS?

I also seem to miss some files from your DSDT list?

**Comment by Stick-Study** [comment]
If the Ethernet is normal, you don't need to worry about it.  You need to download a CineBench R23 and run Muilt Core.  The 13700K should score 29000.  If your scores vary significantly, you may need to add CpuTopologyRebuild.kext. Regarding SSDT, I do not recommend adding too much, as long as it can be used.

About the sleep: If it is indeed caused by CORSAIR iCUE H150i ELITE LCD XT. You can try to plug the USB cable into USB3.0 through a converter. Because the Bluetooth of BCM94360CD often has this problem. My solution is to plug the USB cable into the USB3.0 through a converter.

**Comment by D-an-W** [comment]
Convert to external connector you mean, do you have a picture?

**Comment by Stick-Study** [comment]
> Convert to external connector you mean, do you have a picture?

Not external, but internal
![image](https://user-images.githubusercontent.com/74492520/226944782-44935c26-b122-4ec4-b844-36f6e377469c.jpeg)

**Comment by D-an-W** [comment]
So would loose the USB3 header for case?

**Comment by Stick-Study** [comment]
> So would loose the USB3 header for case?

Yes, you will lose the USB3. So I don't recommend doing this.

**Comment by D-an-W** [comment]
I wonder if USB needs to be attached for macOS once colours etc are set in Windows. Will research more.

**Comment by Stick-Study** [comment]
> I wonder if USB needs to be attached for macOS once colours etc are set in Windows. Will research more. 

Looking forward to your good news.

**Comment by D-an-W** [comment]
USB mapping has resolved the sleep issue without the need for additional hardware, thank you.
